name: 'Install NPM package Dependencies'
description: 'Install NPM package dependencies based on node version and node cache type'
inputs:
  node-version:
    description: 'Node version'
    required: true
    default: '21.6.2'
  node-cache-type:
    description: 'Node cache type'
    required: true
    default: 'npm' # npm or yarn
  github-token:
    description: 'GitHub PAT'
    required: false
    default: ${{ github.token }}
runs:
  using: 'composite'
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.github-token }}
        fetch-depth: 0 # to get all conventional commits

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.node-cache-type }}

    - name: Cache and restore node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-js-${{ hashFiles('**/package-lock.json') }}
        # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: |
          ${{ runner.os }}-js-
          ${{ runner.os }}-

    - name: Install dependencies
      run: 'npm install --legacy-peer-deps'
      shell: bash

    - name: Install missing dependencies
      run: |
        npm i @napi-rs/snappy-linux-x64-gnu @napi-rs/simple-git-linux-x64-gnu sharp -f
      shell: bash
