name: "Install NPM package Dependencies"
description: "Install NPM package dependencies based on node version and node cache type"
inputs:
  node-version:
    description: "Node version"
    required: true
    default: "20"
  node-cache-type:
    description: "Node cache type"
    required: true
    default: "npm" # npm or yarn
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: ${{ inputs.node-cache-type }}

    - name: Cache and restore node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-vitepress-${{ hashFiles('**/package-lock.json') }}
        # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: |
          ${{ runner.os }}-vitepress-
          ${{ runner.os }}-

    - name: Install dependencies
      run: "npm install"
      shell: bash
