name: Copy generative art

on:
  schedule:
    - cron: '0 12 * * *' # Every day at 12 AM
  workflow_dispatch:

concurrency:
  group: 'copy-art-group'
  cancel-in-progress: false

permissions:
  actions: read
  contents: write

jobs:
  copy_generate_art:
    runs-on: ubuntu-latest
    env:
      GENERATIVE_ART_REPO: 'KarChunT/generative-art'
      GENERATIVE_ART_REPO_PATH: 'generative-art'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true
          token: ${{ secrets.PAT }}

      - name: Checkout Generative Art Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ env.GENERATIVE_ART_REPO }}
          path: ${{ env.GENERATIVE_ART_REPO_PATH }}
          # token: ${{ secrets.PAT }}

      - name: Copy Generative Art
        run: |
          # Remove existing art files
          rm -rf public/gallery/art

          # Copy files to the temporary directory
          cp -r ${{ env.GENERATIVE_ART_REPO_PATH }}/output/images/* public/gallery/art

          # Clean up original generative-art directory
          rm -rf ${{ env.GENERATIVE_ART_REPO_PATH }}

      - name: Commit and Push Generated Art
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

          # Check if there are any changes
          if [[ -n "$(git status --porcelain)" ]]; then
            git add .
            git commit -m "art: copy generative art on $(date)"
            git push
          else
            echo "No changes to commit."
          fi
