name: Deployment and generate new release

on:
  workflow_run:
    workflows: ["Bump version and create tag"]
    types:
      - completed

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  check-bump-version-and-create-tag-status:
    uses: ./.github/workflows/check-previous-workflow-status.yml

  build-and-deploy:
    needs: [check-bump-version-and-create-tag-status]
    uses: ./.github/workflows/build-and-deploy.yml

  release:
    runs-on: ubuntu-latest
    needs: [build-and-deploy]
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Determine tag
        run: |
          release_tag="$(node -p "require('./package.json').version")"
          echo "RELEASE_TAG=$release_tag" >> $GITHUB_ENV
      - name: Generate new release
        uses: actions/github-script@v7
        with:
          script: |
            const script = require('.github/scripts/generate-new-release.cjs')
            await script({github, context, core})
