name: Merge PR

on:
  pull_request:
    types:
      - closed
    branches:
      - maindisable

concurrency:
  group: 'merging'
  cancel-in-progress: false

jobs:
  check-pr-merged:
    runs-on: ubuntu-latest
    steps:
      - name: Is PR merged?
        run: |
          if [[ "${{ github.event.pull_request.merged }}" == "true" ]]; then
            echo "### PR Merged ✅" >> $GITHUB_STEP_SUMMARY
          else
            echo "### PR Not Merged ❌" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

  get-version-bump-type:
    runs-on: ubuntu-latest
    needs: [check-pr-merged]
    env:
      FILENAME: 'versionBumpType.txt'
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - name: Get Version Bump Type
        uses: actions/github-script@v7
        id: versionBumpType
        with:
          script: |
            const script = require('.github/scripts/get-version-bump-type.cjs')
            return script({context});

      - name: Save version bump type to file
        run: |
          echo "${{ steps.versionBumpType.outputs.result }}" > ${{ env.FILENAME }}
          echo "### Save Version Bump type: '${{ steps.versionBumpType.outputs.result }}' to file ✅" >> $GITHUB_STEP_SUMMARY

      - name: Archive version bump file
        uses: actions/upload-artifact@v4
        with:
          name: versionBump
          path: ${{ env.FILENAME }}

      - name: Report file archived process
        run: echo "### Version Bump file archived ✅" >> $GITHUB_STEP_SUMMARY
