name: New Post deployment

on:
  push: 
    paths: 
      - 'data/**'
    branches: 
      - 'main'
  workflow_dispatch: 

permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    uses: ./.github/workflows/build-and-deploy.yml
